"""Generate synthetic platform/research datasets under data/platform/.

No real licensed Indian SME dataset was provided with this project (docs/
only contains specifications, not data). Rather than fabricate a dataset and
pretend it is real, this script generates clearly-labelled *synthetic* data
with a documented generation mechanism, seeded for reproducibility, and
writes a metadata.json next to each dataset describing exactly how it was
produced (see docs/DATA_SPECIFICATION.md §10 "Dataset Documentation").

This is what the platform training pipeline (ml/pipeline) trains and
evaluates models against. Nothing here is exposed to SME users — see
AGENTS.md "Data isolation".

Usage:
    python scripts/generate_platform_data.py
"""
import json
from datetime import date, timedelta
from pathlib import Path

import numpy as np
import pandas as pd

RANDOM_SEED = 42
ROOT = Path(__file__).resolve().parent.parent
FORECASTING_DIR = ROOT / "data" / "platform" / "forecasting"
CHURN_DIR = ROOT / "data" / "platform" / "churn"


def generate_forecasting_dataset(rng: np.random.Generator) -> pd.DataFrame:
    """Daily sales time series for synthetic D2C-style product lines.

    Mechanism (documented, not hidden):
    - baseline level + linear trend per series
    - weekly seasonality (weekend uplift)
    - a small number of fixed "festival window" multiplicative bumps per year
      (illustrative only — NOT a claim about real Indian consumer behaviour,
      see docs/PRD.md §5 on not hard-coding festival/GST assumptions)
    - marketing spend as a noisy driver of demand
    - random promotional discount days
    - Gaussian noise
    """
    n_series = 40
    start = date(2023, 1, 1)
    n_days = 730  # 24 months
    dates = [start + timedelta(days=i) for i in range(n_days)]

    rows = []
    for series_id in range(n_series):
        base_level = rng.uniform(20, 200)
        trend_per_day = rng.uniform(-0.02, 0.08)
        weekly_amplitude = rng.uniform(0.05, 0.35)
        price = round(float(rng.uniform(299, 2499)), 2)
        marketing_base = rng.uniform(500, 5000)

        # Fixed illustrative "festival window" day-of-year ranges (Oct-Nov).
        festival_days = {d.timetuple().tm_yday for d in dates if d.month in (10, 11)}

        for i, d in enumerate(dates):
            weekday_factor = 1 + weekly_amplitude * (1 if d.weekday() >= 5 else -0.3)
            festival_factor = 1.4 if d.timetuple().tm_yday in festival_days else 1.0
            marketing_spend = max(
                0.0, marketing_base * (1 + 0.3 * np.sin(i / 30)) + rng.normal(0, marketing_base * 0.1)
            )
            marketing_effect = 1 + 0.15 * np.tanh(marketing_spend / marketing_base - 1)
            promotion = 1 if rng.random() < 0.05 else 0
            promotion_factor = 1.25 if promotion else 1.0

            demand = (
                (base_level + trend_per_day * i)
                * weekday_factor
                * festival_factor
                * marketing_effect
                * promotion_factor
            )
            noise = rng.normal(0, max(1.0, demand * 0.08))
            units_sold = max(0, round(demand + noise))
            effective_price = price * (0.85 if promotion else 1.0)
            revenue = round(units_sold * effective_price, 2)

            rows.append(
                {
                    "series_id": f"S{series_id:03d}",
                    "date": d.isoformat(),
                    "units_sold": units_sold,
                    "revenue": revenue,
                    "price": effective_price,
                    "marketing_spend": round(marketing_spend, 2),
                    "promotion_flag": promotion,
                }
            )

    return pd.DataFrame(rows)


def generate_churn_dataset(rng: np.random.Generator) -> pd.DataFrame:
    """Customer-level snapshot with a churn label generated by a known,
    documented logistic mechanism from behavioural features plus noise —
    this is what makes the dataset useful for *validating* churn models
    (the ground-truth relationship is known here, unlike real data)."""
    n_customers = 6000
    tenure_days = rng.integers(30, 1500, n_customers)
    recency_days = rng.integers(0, 400, n_customers)
    frequency = np.maximum(1, rng.poisson(6, n_customers))
    avg_order_value = rng.gamma(shape=3.0, scale=350, size=n_customers)
    monetary_value = avg_order_value * frequency
    support_tickets = rng.poisson(0.6, n_customers)
    discount_usage_rate = np.clip(rng.beta(2, 5, n_customers), 0, 1)

    # Standardize drivers, then combine into a logit. Higher recency (longer
    # since last purchase) and more support tickets raise churn risk; higher
    # frequency and tenure lower it. Coefficients are illustrative constants
    # for the synthetic generator, not a claim about real customers.
    z_recency = (recency_days - recency_days.mean()) / recency_days.std()
    z_frequency = (frequency - frequency.mean()) / frequency.std()
    z_tenure = (tenure_days - tenure_days.mean()) / tenure_days.std()
    z_tickets = (support_tickets - support_tickets.mean()) / support_tickets.std()

    logit = (
        -0.3
        + 1.1 * z_recency
        - 0.8 * z_frequency
        - 0.4 * z_tenure
        + 0.5 * z_tickets
        + rng.normal(0, 0.5, n_customers)
    )
    churn_probability = 1 / (1 + np.exp(-logit))
    churned = (rng.random(n_customers) < churn_probability).astype(int)

    return pd.DataFrame(
        {
            "customer_id": [f"C{i:05d}" for i in range(n_customers)],
            "tenure_days": tenure_days,
            "recency_days": recency_days,
            "frequency": frequency,
            "avg_order_value": np.round(avg_order_value, 2),
            "monetary_value": np.round(monetary_value, 2),
            "support_tickets": support_tickets,
            "discount_usage_rate": np.round(discount_usage_rate, 4),
            "churned": churned,
        }
    )


def write_dataset(df: pd.DataFrame, out_dir: Path, filename: str, metadata: dict) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_dir / filename, index=False)
    metadata_full = {
        **metadata,
        "rows": len(df),
        "columns": list(df.columns),
        "generated_with_seed": RANDOM_SEED,
    }
    (out_dir / "metadata.json").write_text(json.dumps(metadata_full, indent=2))
    print(f"Wrote {out_dir / filename} ({len(df)} rows)")


def main() -> None:
    rng = np.random.default_rng(RANDOM_SEED)

    forecasting_df = generate_forecasting_dataset(rng)
    write_dataset(
        forecasting_df,
        FORECASTING_DIR,
        "sales_timeseries.csv",
        {
            "dataset_id": "platform-forecasting-v1",
            "name": "Synthetic D2C Sales Time Series",
            "source": "synthetic (scripts/generate_platform_data.py)",
            "license": "N/A - synthetically generated, no third-party data",
            "date_range": ["2023-01-01", "2024-12-31"],
            "preprocessing": [
                "none (raw generator output)",
            ],
            "limitations": [
                "Not derived from real transactions; seasonal/festival effects are illustrative multipliers, not empirically measured Indian consumer behaviour.",
                "Marketing-spend-to-demand relationship is a fixed synthetic function; real elasticity varies by business.",
                "Intended for offline model training/evaluation only — never surfaced to SME users (see AGENTS.md).",
            ],
            "evidence_level": "SYNTHETIC",
        },
    )

    churn_df = generate_churn_dataset(rng)
    write_dataset(
        churn_df,
        CHURN_DIR,
        "customers.csv",
        {
            "dataset_id": "platform-churn-v1",
            "name": "Synthetic Customer Churn Dataset",
            "source": "synthetic (scripts/generate_platform_data.py)",
            "license": "N/A - synthetically generated, no third-party data",
            "date_range": None,
            "preprocessing": [
                "none (raw generator output)",
            ],
            "limitations": [
                "Churn label produced by a known synthetic logistic mechanism over recency/frequency/tenure/support-ticket features — useful for validating model *mechanics*, not for claiming real-world churn accuracy.",
                "Intended for offline model training/evaluation only — never surfaced to SME users (see AGENTS.md).",
            ],
            "evidence_level": "SYNTHETIC",
        },
    )


if __name__ == "__main__":
    main()
